require 'automateit'

module AutomateIt
  # == Common
  #
  # Common is the abstract class that most AutomateIt classes inherit from.
  class Common

    # Output prefix for command execution, e.g. "** ls -la"
    PEXEC = "** "

    # Output prefix for notes, e.g. "=> Something happened"
    PNOTE = "=> "

    # Output prefix for errors, e.g. "!! Something bad happened"
    PERROR = "!! "

    # Boilerplate to add to tops of generated files, warning people not to edit
    # them directly.
  WARNING_BOILERPLATE = "# +---------------------------------------------------------------------+
# | WARNING: Do NOT edit this file directly or your changes will be     |
# | lost. If you need to change this file, you must incorporate your    |
# | changes into the AutomateIt project that created it. If you don't   |
# | know what this means, please talk to your system administrator.     |
# +---------------------------------------------------------------------+
#
"

    # Interpreter instance for this class.
    attr_accessor :interpreter

    # Calls #setup with +options+ for processing.
    def initialize(options={})
      setup(options)
    end

    # Setup the class. Options:
    # * :interpreter - Set the Interpreter.
    def setup(options={})
      @interpreter = options[:interpreter] if options[:interpreter]
    end

    #---[ Interpreter aliases ]---------------------------------------------

    unless defined?(AutomateIt::Interpreter) and AutomateIt::Interpreter === self
      # See Interpreter#log
      def log() @interpreter.log end

      # See Interpreter#noop=
      def noop=(value) @interpreter.noop=(value) end

      # See Interpreter#noop
      def noop(value) @interpreter.noop(value) end

      # See Interpreter#noop?
      def noop?(&block) @interpreter.noop?(&block) end

      # See Interpreter#writing=
      def writing=(value) @interpreter.writing=(value) end

      # See Interpreter#writing
      def writing(value) @interpreter.writing(value) end

      # See Interpreter#writing?
      def writing?(message=nil, &block) @interpreter.writing?(message, &block) end

      # See Interpreter#superuser?
      def superuser?() @interpreter.superuser? end
    end
  end
end
