# Demonstration of how to embed AutomateIt into Rakefile

require "automateit"

# Create an Interpreter for project in current directory.
@interpreter = AutomateIt.new(:project => ".")

# Include methods into Rake session, see "install" task for details.
@interpreter.include_in(self, %w(invoke noop))

desc "Install myapp server"
task :install do
  # This 'invoke' method was created by the 'include_in' call earlier, as a
  # convenient shortcut for: @interpreter.invoke("install")
  invoke "install"
end

desc "Uninstall myapp server"
task :uninstall do
  invoke "uninstall"
end

desc "Preview action, e.g, 'rake preview install'"
task :preview do
  noop true
end
